sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: lt2BO7taahWn6jCyiFbrJYF977eI8DlKO30kjSfmC26PDCi0r6lj8j21k7tVnbsTk+zcJBYtDiwtWrrDgHEfvHgCZKbT7RMLu2TnnSqtjeepoi07X4yXQpYjmiZg+19en3OG/yiHTy2ore0AKpxdmwnlfEEipU1WXzg+0c8BVgM=
  email:
    recipients:
      secure: TBvY66Iw9WIlkFZFTcKklpnh+OzgyfqR+mYqMwTnrCb+vg60/8Lny538Jp3G03dUW3ZuCtRAy9DK07228lDgS+DRFrMLhvE4WXTVpxCaCzCCOTXzVZVSQsBaWZsSlqCgNx8wX9sTvUPd/uTiTbUzVeuHIREWGDVqHFA+1iVnhMQ=
